package com.incomm.cca.model.constant;

import java.util.HashSet;
import java.util.Set;

public class PropertySystemName extends PseudoEnum {

    public static final String AD_ROLES_MASTER_LIST = "AD_ROLES_MASTER_LIST";
    public static final String AMEX_GIFT_CARD_PRODUCT_CODES = "AMEX_GIFT_CARD_PRODUCT_CODES";
    public static final String APLS_TIMEOUT = "APLS_TIMEOUT";
    public static final String BOL_CANCEL_ORDER_SUPPORTED_STATUSES = "BOL_CANCEL_ORDER_SUPPORTED_STATUSES";
    public static final String BOL_HOLD_ORDER_SUPPORTED_STATUSES = "BOL_HOLD_ORDER_SUPPORTED_STATUSES";
    public static final String BOL_REFUND_ORDER_SUPPORTED_STATUSES = "BOL_REFUND_ORDER_SUPPORTED_STATUSES";
    public static final String CANCEL_ORDER_SUPPORTED_STATUSES = "CANCEL_ORDER_SUPPORTED_STATUSES";
    public static final String DEFAULT_CASHTIE_HISTORY_DATE_RANGE = "DEFAULT_CASHTIE_HISTORY_DATE_RANGE";
    public static final String DEFAULT_CUSTOMER_HISTORY_DATE_RANGE = "DEFAULT_CUSTOMER_HISTORY_DATE_RANGE";
    public static final String DEFAULT_DROPPED_CALL_WRAP_UP_CODE_ID = "DEFAULT_DROPPED_CALL_WRAP_UP_CODE_ID";
    public static final String DEFAULT_GC_PRODUCT_HISTORY_DATE_RANGE = "DEFAULT_GC_PRODUCT_HISTORY_DATE_RANGE";
    public static final String DEFAULT_LOCATION_HISTORY_DATE_RANGE = "DEFAULT_LOCATION_HISTORY_DATE_RANGE";
    public static final String DEFAULT_MM_PRODUCT_HISTORY_DATE_RANGE = "DEFAULT_MM_PRODUCT_HISTORY_DATE_RANGE";
    public static final String DEFAULT_SEND_DISPUTE_FORM_BCC_DISTRIBUTION = "DEFAULT_SEND_DISPUTE_FORM_BCC_DISTRIBUTION";
    public static final String DEFAULT_SEND_DISPUTE_FORM_BCC_DISTRIBUTION_GIFT_CARD = "DEFAULT_SEND_DISPUTE_FORM_BCC_DISTRIBUTION_GIFT_CARD";
    public static final String DEFAULT_SEND_FORM_FAX_DISTRIBUTION = "DEFAULT_SEND_FORM_FAX_DISTRIBUTION";
    public static final String DEFAULT_SEND_FORM_FAX_DISTRIBUTION_DISPUTES = "DEFAULT_SEND_FORM_FAX_DISTRIBUTION_DISPUTES";
    public static final String DEFAULT_SEND_FORM_FAX_DISTRIBUTION_DISPUTES_GIFT_CARD = "DEFAULT_SEND_FORM_FAX_DISTRIBUTION_DISPUTES_GIFT_CARD";
    public static final String DEFAULT_SEND_FORM_MAIL_DISTRIBUTION = "DEFAULT_SEND_FORM_MAIL_DISTRIBUTION";
    public static final String DEFAULT_SEND_FORM_MAIL_DISTRIBUTION_DISPUTES = "DEFAULT_SEND_FORM_MAIL_DISTRIBUTION_DISPUTES";
    public static final String DEFAULT_SEND_FORM_MAIL_DISTRIBUTION_DISPUTES_GIFT_CARD = "DEFAULT_SEND_FORM_MAIL_DISTRIBUTION_DISPUTES_GIFT_CARD";
    public static final String DEFAULT_WRAP_UP_CODE_ID = "DEFAULT_WRAP_UP_CODE_ID";
    public static final String DFC_MOMENTUM_MC_PRODUCT_CODES = "DFC_MOMENTUM_MC_PRODUCT_CODES";
    public static final String DFC_MOMENTUM_VISA_PRODUCT_CODES = "DFC_MOMENTUM_VISA_PRODUCT_CODES";
    public static final String DFC_TITANIUM_MC_PRODUCT_CODES = "DFC_TITANIUM_MC_PRODUCT_CODES";
    public static final String ECOMM_CANCEL_ORDER_BALANCE_ADJUSTMENT_REASON_CODE = "ECOMM_CANCEL_ORDER_BALANCE_ADJUSTMENT_REASON_CODE";
    public static final String ECOMM_CANCEL_ORDER_JOB_NAME = "ECOMM_CANCEL_ORDER_JOB_NAME";
    public static final String FEDEX_TRACKING_URL = "FEDEX_TRACKING_URL";
    public static final String GC_REQUEST_RESPONSE_MAPPING_DATE = "GC_REQUEST_RESPONSE_MAPPING_DATE";
    public static final String I3_WRAP_UP_SEND_DELAY = "I3_WRAP_UP_SEND_DELAY";
    public static final String INCOMM_NO_REPLY_SENDER = "INCOMM_NO_REPLY_SENDER";
    public static final String INCOMM_PRIVACY_REQUEST_RECIPIENT = "INCOMM_PRIVACY_REQUEST_RECIPIENT";
    public static final String INCOMM_USER_DEACTIVATION_RECIPIENT = "INCOMM_USER_DEACTIVATION_RECIPIENT";
    public static final String JIRA_COLLECTOR_URL = "JIRA_COLLECTOR_URL";
    public static final String JIRA_TIMEOUT = "JIRA_TIMEOUT";
    public static final String NEW_USER_DEFAULT_ROLE_ID = "NEW_USER_DEFAULT_ROLE_ID";
    public static final String OP_CODE_MAPPING_CACHE_DATE = "OP_CODE_MAPPING_CACHE_DATE";
    public static final String REFUND_ORDER_SUPPORTED_STATUSES = "REFUND_ORDER_SUPPORTED_STATUSES";
    public static final String SLOW_RESPONSE_MESSAGE_DELAY = "SLOW_RESPONSE_MESSAGE_DELAY";
    public static final String TROUBLESHOOTING_SESSION_DURATION = "TROUBLESHOOTING_SESSION_DURATION";
    public static final String WEB_SOCKET_SUBSCRIPTION_REQUEST = "WEB_SOCKET_SUBSCRIPTION_REQUEST";
    private static Set<String> values = new HashSet<>();

    static {
        values.add(AD_ROLES_MASTER_LIST);
        values.add(AMEX_GIFT_CARD_PRODUCT_CODES);
        values.add(APLS_TIMEOUT);
        values.add(BOL_CANCEL_ORDER_SUPPORTED_STATUSES);
        values.add(BOL_HOLD_ORDER_SUPPORTED_STATUSES);
        values.add(BOL_REFUND_ORDER_SUPPORTED_STATUSES);
        values.add(CANCEL_ORDER_SUPPORTED_STATUSES);
        values.add(DEFAULT_CASHTIE_HISTORY_DATE_RANGE);
        values.add(DEFAULT_CUSTOMER_HISTORY_DATE_RANGE);
        values.add(DEFAULT_DROPPED_CALL_WRAP_UP_CODE_ID);
        values.add(DEFAULT_GC_PRODUCT_HISTORY_DATE_RANGE);
        values.add(DEFAULT_LOCATION_HISTORY_DATE_RANGE);
        values.add(DEFAULT_MM_PRODUCT_HISTORY_DATE_RANGE);
        values.add(DEFAULT_SEND_DISPUTE_FORM_BCC_DISTRIBUTION);
        values.add(DEFAULT_SEND_DISPUTE_FORM_BCC_DISTRIBUTION_GIFT_CARD);
        values.add(DEFAULT_SEND_FORM_FAX_DISTRIBUTION);
        values.add(DEFAULT_SEND_FORM_FAX_DISTRIBUTION_DISPUTES);
        values.add(DEFAULT_SEND_FORM_FAX_DISTRIBUTION_DISPUTES_GIFT_CARD);
        values.add(DEFAULT_SEND_FORM_MAIL_DISTRIBUTION);
        values.add(DEFAULT_SEND_FORM_MAIL_DISTRIBUTION_DISPUTES);
        values.add(DEFAULT_SEND_FORM_MAIL_DISTRIBUTION_DISPUTES_GIFT_CARD);
        values.add(DEFAULT_WRAP_UP_CODE_ID);
        values.add(DFC_MOMENTUM_MC_PRODUCT_CODES);
        values.add(DFC_MOMENTUM_VISA_PRODUCT_CODES);
        values.add(DFC_TITANIUM_MC_PRODUCT_CODES);
        values.add(ECOMM_CANCEL_ORDER_BALANCE_ADJUSTMENT_REASON_CODE);
        values.add(ECOMM_CANCEL_ORDER_JOB_NAME);
        values.add(FEDEX_TRACKING_URL);
        values.add(GC_REQUEST_RESPONSE_MAPPING_DATE);
        values.add(I3_WRAP_UP_SEND_DELAY);
        values.add(JIRA_COLLECTOR_URL);
        values.add(JIRA_TIMEOUT);
        values.add(NEW_USER_DEFAULT_ROLE_ID);
        values.add(INCOMM_NO_REPLY_SENDER);
        values.add(INCOMM_PRIVACY_REQUEST_RECIPIENT);
        values.add(INCOMM_USER_DEACTIVATION_RECIPIENT);
        values.add(OP_CODE_MAPPING_CACHE_DATE);
        values.add(REFUND_ORDER_SUPPORTED_STATUSES);
        values.add(SLOW_RESPONSE_MESSAGE_DELAY);
        values.add(TROUBLESHOOTING_SESSION_DURATION);
        values.add(WEB_SOCKET_SUBSCRIPTION_REQUEST);
    }

    @Override
    public Set<String> getValues() {
        return values;
    }

    public static String valueOf(String value) {
        return new PropertySystemName().validateValue(value);
    }
}
