CREATE TABLE session_status (
    id   BIGINT IDENTITY (1, 1) NOT NULL,
    name VARCHAR(64)            NOT NULL,
    CONSTRAINT pk_session_status PRIMARY KEY (id),
    CONSTRAINT uk_session_status_name UNIQUE (name)
);

CREATE TABLE session_type_session_status (
    session_type_id   BIGINT NOT NULL,
    session_status_id BIGINT NOT NULL,
    CONSTRAINT pk_session_type_session_status PRIMARY KEY (session_type_id, session_status_id),
    CONSTRAINT fk_session_type_session_status_session_type FOREIGN KEY (session_type_id) REFERENCES session_type (id),
    CONSTRAINT fk_session_type_session_status_session_status FOREIGN KEY (session_status_id) REFERENCES session_status (id)
);

GO

INSERT INTO session_status (name)
VALUES ('ACTIVE'),
       ('CLOSED'),
       ('AWAITING_DOCS'),
       ('WORKING'),
       ('CALLBACK'),
       ('ACTIVATION_REVERSAL'),
       ('REPLACEMENT'),
       ('AWAITING_ADDITIONAL_DOCS'),
       ('AWAITING_MERCH_RESPONSE'),
       ('CALLBACK_AWAITING_ADDITIONAL_DOCS');

INSERT INTO session_type_session_status (session_type_id, session_status_id)
VALUES ((SELECT id FROM session_type WHERE name = 'GENERAL'), (SELECT id FROM session_status WHERE name = 'ACTIVE')),
       ((SELECT id FROM session_type WHERE name = 'GENERAL'), (SELECT id FROM session_status WHERE name = 'CLOSED')),
       ((SELECT id FROM session_type WHERE name = 'CALL'), (SELECT id FROM session_status WHERE name = 'ACTIVE')),
       ((SELECT id FROM session_type WHERE name = 'CALL'), (SELECT id FROM session_status WHERE name = 'CLOSED')),
       ((SELECT id FROM session_type WHERE name = 'BAD_CREDIT'), (SELECT id FROM session_status WHERE name = 'ACTIVE')),
       ((SELECT id FROM session_type WHERE name = 'BAD_CREDIT'), (SELECT id FROM session_status WHERE name = 'CLOSED')),
       ((SELECT id FROM session_type WHERE name = 'BAD_CREDIT'),
        (SELECT id FROM session_status WHERE name = 'AWAITING_DOCS')),
       ((SELECT id FROM session_type WHERE name = 'BAD_CREDIT'),
        (SELECT id FROM session_status WHERE name = 'WORKING')),
       ((SELECT id FROM session_type WHERE name = 'BAD_CREDIT'),
        (SELECT id FROM session_status WHERE name = 'CALLBACK')),
       ((SELECT id FROM session_type WHERE name = 'BAD_CREDIT'),
        (SELECT id FROM session_status WHERE name = 'ACTIVATION_REVERSAL')),
       ((SELECT id FROM session_type WHERE name = 'BAD_CREDIT'),
        (SELECT id FROM session_status WHERE name = 'REPLACEMENT')),
       ((SELECT id FROM session_type WHERE name = 'CONSUMED_CARD'),
        (SELECT id FROM session_status WHERE name = 'ACTIVE')),
       ((SELECT id FROM session_type WHERE name = 'CONSUMED_CARD'),
        (SELECT id FROM session_status WHERE name = 'CLOSED')),
       ((SELECT id FROM session_type WHERE name = 'CONSUMED_CARD'),
        (SELECT id FROM session_status WHERE name = 'AWAITING_DOCS')),
       ((SELECT id FROM session_type WHERE name = 'CONSUMED_CARD'),
        (SELECT id FROM session_status WHERE name = 'WORKING')),
       ((SELECT id FROM session_type WHERE name = 'CONSUMED_CARD'),
        (SELECT id FROM session_status WHERE name = 'CALLBACK')),
       ((SELECT id FROM session_type WHERE name = 'CONSUMED_CARD'),
        (SELECT id FROM session_status WHERE name = 'ACTIVATION_REVERSAL')),
       ((SELECT id FROM session_type WHERE name = 'CONSUMED_CARD'),
        (SELECT id FROM session_status WHERE name = 'REPLACEMENT')),
       ((SELECT id FROM session_type WHERE name = 'CONSUMED_CARD'),
        (SELECT id FROM session_status WHERE name = 'AWAITING_ADDITIONAL_DOCS')),
       ((SELECT id FROM session_type WHERE name = 'CONSUMED_CARD'),
        (SELECT id FROM session_status WHERE name = 'AWAITING_MERCH_RESPONSE')),
       ((SELECT id FROM session_type WHERE name = 'CONSUMED_CARD'),
        (SELECT id FROM session_status WHERE name = 'CALLBACK_AWAITING_ADDITIONAL_DOCS')),
       ((SELECT id FROM session_type WHERE name = 'DAMAGED_PINS'),
        (SELECT id FROM session_status WHERE name = 'ACTIVE')),
       ((SELECT id FROM session_type WHERE name = 'DAMAGED_PINS'),
        (SELECT id FROM session_status WHERE name = 'CLOSED')),
       ((SELECT id FROM session_type WHERE name = 'DAMAGED_PINS'),
        (SELECT id FROM session_status WHERE name = 'AWAITING_DOCS')),
       ((SELECT id FROM session_type WHERE name = 'DAMAGED_PINS'),
        (SELECT id FROM session_status WHERE name = 'WORKING')),
       ((SELECT id FROM session_type WHERE name = 'DAMAGED_PINS'),
        (SELECT id FROM session_status WHERE name = 'CALLBACK')),
       ((SELECT id FROM session_type WHERE name = 'DAMAGED_PINS'),
        (SELECT id FROM session_status WHERE name = 'ACTIVATION_REVERSAL')),
       ((SELECT id FROM session_type WHERE name = 'DAMAGED_PINS'),
        (SELECT id FROM session_status WHERE name = 'REPLACEMENT')),
       ((SELECT id FROM session_type WHERE name = 'DISPUTE'), (SELECT id FROM session_status WHERE name = 'ACTIVE')),
       ((SELECT id FROM session_type WHERE name = 'DISPUTE'), (SELECT id FROM session_status WHERE name = 'CLOSED')),
       ((SELECT id FROM session_type WHERE name = 'DISPUTE'),
        (SELECT id FROM session_status WHERE name = 'AWAITING_DOCS')),
       ((SELECT id FROM session_type WHERE name = 'DISPUTE'), (SELECT id FROM session_status WHERE name = 'WORKING')),
       ((SELECT id FROM session_type WHERE name = 'DISPUTE'), (SELECT id FROM session_status WHERE name = 'CALLBACK')),
       ((SELECT id FROM session_type WHERE name = 'DISPUTE'),
        (SELECT id FROM session_status WHERE name = 'ACTIVATION_REVERSAL')),
       ((SELECT id FROM session_type WHERE name = 'DISPUTE'),
        (SELECT id FROM session_status WHERE name = 'REPLACEMENT')),
       ((SELECT id FROM session_type WHERE name = 'ECOMM_FRAUD'),
        (SELECT id FROM session_status WHERE name = 'ACTIVE')),
       ((SELECT id FROM session_type WHERE name = 'ECOMM_FRAUD'),
        (SELECT id FROM session_status WHERE name = 'CLOSED')),
       ((SELECT id FROM session_type WHERE name = 'ECOMM_FRAUD'),
        (SELECT id FROM session_status WHERE name = 'AWAITING_DOCS')),
       ((SELECT id FROM session_type WHERE name = 'ECOMM_FRAUD'),
        (SELECT id FROM session_status WHERE name = 'WORKING')),
       ((SELECT id FROM session_type WHERE name = 'ECOMM_FRAUD'),
        (SELECT id FROM session_status WHERE name = 'CALLBACK')),
       ((SELECT id FROM session_type WHERE name = 'ECOMM_FRAUD'),
        (SELECT id FROM session_status WHERE name = 'ACTIVATION_REVERSAL')),
       ((SELECT id FROM session_type WHERE name = 'ECOMM_FRAUD'),
        (SELECT id FROM session_status WHERE name = 'REPLACEMENT')),
       ((SELECT id FROM session_type WHERE name = 'LAW_ENFORCEMENT'),
        (SELECT id FROM session_status WHERE name = 'ACTIVE')),
       ((SELECT id FROM session_type WHERE name = 'LAW_ENFORCEMENT'),
        (SELECT id FROM session_status WHERE name = 'CLOSED')),
       ((SELECT id FROM session_type WHERE name = 'LAW_ENFORCEMENT'),
        (SELECT id FROM session_status WHERE name = 'AWAITING_DOCS')),
       ((SELECT id FROM session_type WHERE name = 'LAW_ENFORCEMENT'),
        (SELECT id FROM session_status WHERE name = 'WORKING')),
       ((SELECT id FROM session_type WHERE name = 'LAW_ENFORCEMENT'),
        (SELECT id FROM session_status WHERE name = 'CALLBACK')),
       ((SELECT id FROM session_type WHERE name = 'LAW_ENFORCEMENT'),
        (SELECT id FROM session_status WHERE name = 'ACTIVATION_REVERSAL')),
       ((SELECT id FROM session_type WHERE name = 'LAW_ENFORCEMENT'),
        (SELECT id FROM session_status WHERE name = 'REPLACEMENT')),
       ((SELECT id FROM session_type WHERE name = 'MERCHANT_FRAUD'),
        (SELECT id FROM session_status WHERE name = 'ACTIVE')),
       ((SELECT id FROM session_type WHERE name = 'MERCHANT_FRAUD'),
        (SELECT id FROM session_status WHERE name = 'CLOSED')),
       ((SELECT id FROM session_type WHERE name = 'MERCHANT_FRAUD'),
        (SELECT id FROM session_status WHERE name = 'AWAITING_DOCS')),
       ((SELECT id FROM session_type WHERE name = 'MERCHANT_FRAUD'),
        (SELECT id FROM session_status WHERE name = 'WORKING')),
       ((SELECT id FROM session_type WHERE name = 'MERCHANT_FRAUD'),
        (SELECT id FROM session_status WHERE name = 'CALLBACK')),
       ((SELECT id FROM session_type WHERE name = 'MERCHANT_FRAUD'),
        (SELECT id FROM session_status WHERE name = 'ACTIVATION_REVERSAL')),
       ((SELECT id FROM session_type WHERE name = 'MERCHANT_FRAUD'),
        (SELECT id FROM session_status WHERE name = 'REPLACEMENT')),
       ((SELECT id FROM session_type WHERE name = 'OTHER_FRAUD'),
        (SELECT id FROM session_status WHERE name = 'ACTIVE')),
       ((SELECT id FROM session_type WHERE name = 'OTHER_FRAUD'),
        (SELECT id FROM session_status WHERE name = 'CLOSED')),
       ((SELECT id FROM session_type WHERE name = 'OTHER_FRAUD'),
        (SELECT id FROM session_status WHERE name = 'AWAITING_DOCS')),
       ((SELECT id FROM session_type WHERE name = 'OTHER_FRAUD'),
        (SELECT id FROM session_status WHERE name = 'WORKING')),
       ((SELECT id FROM session_type WHERE name = 'OTHER_FRAUD'),
        (SELECT id FROM session_status WHERE name = 'CALLBACK')),
       ((SELECT id FROM session_type WHERE name = 'OTHER_FRAUD'),
        (SELECT id FROM session_status WHERE name = 'ACTIVATION_REVERSAL')),
       ((SELECT id FROM session_type WHERE name = 'OTHER_FRAUD'),
        (SELECT id FROM session_status WHERE name = 'REPLACEMENT')),
       ((SELECT id FROM session_type WHERE name = 'PAYPAL_REDEMPTION_ISSUE'),
        (SELECT id FROM session_status WHERE name = 'ACTIVE')),
       ((SELECT id FROM session_type WHERE name = 'PAYPAL_REDEMPTION_ISSUE'),
        (SELECT id FROM session_status WHERE name = 'CLOSED')),
       ((SELECT id FROM session_type WHERE name = 'PAYPAL_REDEMPTION_ISSUE'),
        (SELECT id FROM session_status WHERE name = 'AWAITING_DOCS')),
       ((SELECT id FROM session_type WHERE name = 'PAYPAL_REDEMPTION_ISSUE'),
        (SELECT id FROM session_status WHERE name = 'WORKING')),
       ((SELECT id FROM session_type WHERE name = 'PAYPAL_REDEMPTION_ISSUE'),
        (SELECT id FROM session_status WHERE name = 'CALLBACK')),
       ((SELECT id FROM session_type WHERE name = 'PAYPAL_REDEMPTION_ISSUE'),
        (SELECT id FROM session_status WHERE name = 'ACTIVATION_REVERSAL')),
       ((SELECT id FROM session_type WHERE name = 'PAYPAL_REDEMPTION_ISSUE'),
        (SELECT id FROM session_status WHERE name = 'REPLACEMENT'));

