export enum CodexType {
  CCA_CCL_GIFT_CHANGE_STATUS  = 'CCA_CCL_GIFT_CHANGE_STATUS',
  CCA_GREENCARD_CHANGE_STATUS = 'CCA_GREENCARD_CHANGE_STATUS',
  CCA_VMS_GIFT_CHANGE_STATUS  = 'CCA_VMS_GIFT_CHANGE_STATUS',
  CCA_VMS_GPR_CHANGE_STATUS   = 'CCA_VMS_GPR_CHANGE_STATUS'
}
