export enum SearchActionType {
  CLEAR_CURRENT_SEARCH_TYPE  = 'CLEAR_CURRENT_SEARCH_TYPE',
  CLEAR_SEARCH_RESULTS       = 'CLEAR_SEARCH_RESULTS',
  CLEAR_SEARCH_TYPES         = 'CLEAR_SEARCH_TYPES',
  CLEAR_STATE                = 'CLEAR_STATE',
  LOAD_SEARCH_TYPES          = 'LOAD_SEARCH_TYPES',
  RESET_PARAMETERS           = 'RESET_PARAMETERS',
  SEARCHING                  = 'SEARCHING',
  SELECT_SEARCH_TYPE         = 'SELECT_SEARCH_TYPE',
  SET_SEARCH_PARAMETERS      = 'SET_SEARCH_PARAMETERS',
  SET_SEARCH_RESULTS         = 'SET_SEARCH_RESULTS',
  SET_TEXT_FILTER            = 'SET_TEXT_FILTER',
  UPDATE_SEARCH_TYPE         = 'UPDATE_SEARCH_TYPE'
}
