export enum SelectionAlertType {
  FRAUD_CASE             = 'FRAUD_CASE',
  FRAUD_CASE_HISTORY     = 'FRAUD_CASE_HISTORY',
  FRAUD_CUSTOMER_ACCOUNT = 'FRAUD_CUSTOMER_ACCOUNT',
  JOB_IN_PROGRESS        = 'JOB_IN_PROGRESS',
  ORDER_ON_HOLD          = 'ORDER_ON_HOLD'
}
