export enum SearchTypeType {
  ALDER            = 'ALDER',
  CCL_GIFT         = 'CCL_GIFT',
  DDP              = 'DDP',
  BOL_ORDER        = 'BOL_ORDER',
  ECOMM_ORDER      = 'ECOMM_ORDER',
  ENCOR            = 'ENCOR',
  FASTCARD_FASTPIN = 'FASTCARD_FASTPIN',
  FINANCIAL_GIFT   = 'FINANCIAL_GIFT',
  JIRA             = 'JIRA',
  KYC_FAILURE      = 'KYC_FAILURE',
  LOCATION         = 'LOCATION',
  LOTTERY          = 'LOTTERY',
  SERVE            = 'SERVE',
  SESSION          = 'SESSION',
  VANILLA_DIRECT   = 'VANILLA_DIRECT',
  VMS_GIFT         = 'VMS_GIFT',
  VMS_GPR          = 'VMS_GPR',
  VRN_SWIPE_RELOAD = 'VRN_SWIPE_RELOAD'
}
