export enum TogglzType {
  BYPASS_PIN_CHECK_ON_ACTIVATE_CARD          = 'BYPASS_PIN_CHECK_ON_ACTIVATE_CARD',
  SHOW_GC_CARD_NUMBER_IN_TRANSACTION_HISTORY = 'SHOW_GC_CARD_NUMBER_IN_TRANSACTION_HISTORY',
  VMS_ORDER_NUMBER_LINK                      = 'VMS_ORDER_NUMBER_LINK'
}
