package com.incomm.cca.model.enums.session;

public enum SessionComponentType {
    CALL_COMPONENT,
    CARDS_COMPONENT,
    COMPLAINT_COMPONENT,
    CUSTOMER_COMPONENT,
    DISPUTE_COMPONENT,
    DOCUMENTS_COMPONENT,
    ENCOR_COMPONENT,
    GENERAL_COMPONENT,
    LAW_ENFORCEMENT_COMPONENT,
    MERCHANT_COMPONENT,
    PRIVACY_COMPONENT,
    RECEIPT_COMPONENT,
    REFUND_REQUEST_COMPONENT
}
