export enum AuthenticationStatus {
  NOT_ATTEMPTED         = 'NOT_ATTEMPTED',
  AUTHENTICATION_FAILED = 'NOT_AUTHENTICATED',
  AUTHENTICATING        = 'AUTHENTICATING',
  AUTHENTICATED         = 'AUTHENTICATED'
}
