CREATE TABLE complaint_component (
    id                     BIGINT IDENTITY (1,1) NOT NULL,
    session_id             BIGINT                NOT NULL,
    bank_id                BIGINT                NOT NULL,
    category_id            BIGINT,
    cause_id               BIGINT,
    department_id          BIGINT,
    discrimination_type_id BIGINT,
    identifier_id          BIGINT,
    source_id              BIGINT,
    type_id                BIGINT,
    first_name             VARCHAR(64),
    last_name              VARCHAR(64),
    compensation           VARCHAR(64),
    complaint              VARCHAR(500),
    enhancements_needed    VARCHAR(500),
    is_regulatory          BIT                   NOT NULL,
    is_verbal              BIT                   NOT NULL,
    is_written             BIT                   NOT NULL,
    postal_code            VARCHAR(64),
    resolution             VARCHAR(500),
    created_by             BIGINT                NOT NULL,
    created_date           DATETIME2             NOT NULL,
    modified_by            BIGINT                NOT NULL,
    modified_date          DATETIME2             NOT NULL,
    CONSTRAINT pk_complaint_component PRIMARY KEY (id),
    CONSTRAINT fk_complaint_component_session_id FOREIGN KEY (session_id) REFERENCES cca_session(id),
    CONSTRAINT fk_complaint_component_bank_id FOREIGN KEY (bank_id) REFERENCES bank(id),
    CONSTRAINT fk_complaint_component_category_id FOREIGN KEY (category_id) REFERENCES complaint_category(id),
    CONSTRAINT fk_complaint_component_cause_id FOREIGN KEY (cause_id) REFERENCES complaint_cause(id),
    CONSTRAINT fk_complaint_component_department_id FOREIGN KEY (department_id) REFERENCES complaint_department(id),
    CONSTRAINT fk_complaint_component_discrimination_type_id FOREIGN KEY (discrimination_type_id) REFERENCES complaint_discrimination_type(id),
    CONSTRAINT fk_complaint_component_identifier_id FOREIGN KEY (identifier_id) REFERENCES identifier(id),
    CONSTRAINT fk_complaint_component_source_id FOREIGN KEY (source_id) REFERENCES complaint_source(id),
    CONSTRAINT fk_complaint_component_type_id FOREIGN KEY (type_id) REFERENCES complaint_type(id),
    CONSTRAINT fk_complaint_component_created_by FOREIGN KEY (created_by) REFERENCES cca_user(id),
    CONSTRAINT fk_complaint_component_modified_by FOREIGN KEY (modified_by) REFERENCES cca_user(id)
);

CREATE INDEX idx_complaint_component_session_id ON complaint_component(session_id);
CREATE INDEX idx_complaint_component_bank_id ON complaint_component(bank_id);