UPDATE cca_property
SET
    value = 'RISK_SUCCESS,RISK_PENDING,RISK_DECLINED,ORDER_INIT,HOLD,FRAUD_INIT,FRAUD_FAILED,FRAUD_RETRYING,FRAUD_PENDING,FRAUD_SUCCESS,FRAUD_DECLINED,FULFILLMENT_READY'
WHERE system_name = 'CANCEL_ORDER_SUPPORTED_STATUSES';

UPDATE cca_property
SET value = 'PAYMENT_COMPLETE,COMPLETE'
WHERE system_name = 'REFUND_ORDER_SUPPORTED_STATUSES';