export enum SupportActionType {

  CLEAR_STATE                      = 'CLEAR_STATE',
  LOAD_BALANCE_ADJUSTMENT_ACTIVITY = 'LOAD_BALANCE_ADJUSTMENT_ACTIVITY',
  LOAD_CANARY_INFO                 = 'LOAD_CANARY_INFO',
  LOAD_IDENTIFICATION_TYPES        = 'LOAD_IDENTIFICATION_TYPES',
  LOAD_OCCUPATIONS                 = 'LOAD_OCCUPATIONS',
  LOAD_PARTNERS                    = 'LOAD_PARTNERS',
  LOAD_PLATFORM_STATUS_VALUES      = 'LOAD_PLATFORM_STATUS_VALUES',
  LOAD_PROPERTIES                  = 'LOAD_PROPERTIES',
  LOAD_SESSION_DEFINITIONS         = 'LOAD_SESSION_DEFINITIONS',
  LOAD_TEAMS                       = 'LOAD_TEAMS',
  LOAD_TOGGLZ                      = 'LOAD_TOGGLZ',
  RESET_SESSION_TIMEOUT            = 'RESET_SESSION_TIMEOUT',
  SET_INIT_COMPLETE                 = 'SET_INIT_COMPLETE',
  SET_PRODUCT_DESCRIPTION_CONTAINER = 'SET_PRODUCT_DESCRIPTION_CONTAINER',
  SET_PRODUCT_REASON_CODES          = 'SET_PRODUCT_REASON_CODES'
}
