package com.incomm.cca.util.export.enums;

public enum HTMLDocumentComponent {
    DEFAULT_FOOTER,
    LOCATION_DETAILS,
    LOCATION_HISTORY_DETAILS,
    PRODUCT_DETAILS,
    PRODUCT_HISTORY_DETAILS,
    CUSTOMER_DETAILS,
    CUSTOMER_HISTORY_DETAILS,
    TERMINAL_DETAILS,
    TRANSACTION_SUMMARY
}
