export enum SessionComponentType {
  CALL              = 'CALL_COMPONENT',
  CARDS             = 'CARDS_COMPONENT',
  COMPLAINT         = 'COMPLAINT_COMPONENT',
  CUSTOMER          = 'CUSTOMER_COMPONENT',
  DISPUTE_COMPONENT = 'DISPUTE_COMPONENT',
  DOCUMENTS         = 'DOCUMENTS_COMPONENT',
  ENCOR             = 'ENCOR_COMPONENT',
  LAW_ENFORCEMENT   = 'LAW_ENFORCEMENT_COMPONENT',
  MERCHANT          = 'MERCHANT_COMPONENT',
  RECEIPT           = 'RECEIPT_COMPONENT',
  REFUND_REQUEST    = 'REFUND_REQUEST_COMPONENT'
}
