export enum ExportComponentType {
  CUSTOMER_DETAILS         = 'CUSTOMER_DETAILS',
  CUSTOMER_HISTORY_DETAILS = 'CUSTOMER_HISTORY_DETAILS',
  DEFAULT_FOOTER           = 'DEFAULT_FOOTER',
  LOCATION_DETAILS         = 'LOCATION_DETAILS',
  LOCATION_HISTORY_DETAILS = 'LOCATION_HISTORY_DETAILS',
  PRODUCT_DETAILS          = 'PRODUCT_DETAILS',
  PRODUCT_HISTORY_DETAILS  = 'PRODUCT_HISTORY_DETAILS',
  TERMINAL_DETAILS         = 'TERMINAL_DETAILS',
  TRANSACTION_SUMMARY      = 'TRANSACTION_SUMMARY'
}
