export enum DateFormat {
  MOMENT_DATE_ISO_FORMAT = 'YYYY-MM-DD',
  MOMENT_DATE_FORMAT = 'MM/DD/YYYY',
  MOMENT_DATE_TIME_FORMAT = 'MM/DD/YYYY hh:mm A',
  CSCORE_DATE_TIME_FORMAT = 'MM/DD/YYYY HH:mm Z',
}