name: ci

on:
  workflow_dispatch:
  push:
    branches: master

jobs:
  main:
    runs-on: ubuntu-latest
    steps:
      -
        name: Set up QEMU
        uses: docker/setup-qemu-action@v1
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      
      - uses: jfrog/setup-jfrog-cli@v1
        env:
          JF_ARTIFACTORY_1: ${{ secrets.ARTIFACTORY_TOKEN }}
      - run: |
          jfrog rt config --interactive=false --enc-password=true --url=https://docker.maven.incomm.com/ --apikey=${{ secrets.ARTIFACTORY_TOKEN }}
          jfrog rt use docker.maven.incomm.com
          jfrog rt ping
          
#         name: Login to DockerHub
#         uses: docker/login-action@v1
#         with:
#           username: ${{ secrets.ARTIFACTORY_UNAME }}
#           password: ${{ secrets.ARTIFACTORY_PWORD }}
      -
        name: Build and push
        id: docker_build
        uses: docker/build-push-action@v2
        with:
          push: true
          tags: user/app:latest
          secrets: |
            GIT_AUTH_TOKEN=${{ secrets.ARTIFACTORY_TOKEN}}
#          build-args: |
#            arg1=value1
#            arg2=value2
      -
        name: Image digest
        run: echo ${{ steps.docker_build.outputs.digest }}
