name: docker-image push ci

on:
  workflow_dispatch:
  push:
      paths:
      - '.github/workflows/docker-image**'
  pull_request:
    branches: [ main ]

jobs:
  main:
    runs-on: ubuntu-latest
    steps:
      -
        name: Set up QEMU
        uses: docker/setup-qemu-action@v1
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      -    
        name: Login to ACR
        uses: docker/login-action@v1
        with:
          registry: docker.maven.com
          username: ${{ secrets.ARTIFACTORY_UNAME }}
          password: ${{ secrets.ARTIFACTORY_PWORD }}
#         name: Login to DockerHub
#         uses: docker/login-action@v1
#         with:
#           username: ${{ secrets.ARTIFACTORY_UNAME }}
#           password: ${{ secrets.ARTIFACTORY_PWORD }}
      -
        name: Build and push
        id: docker_build
        uses: docker/build-push-action@v2
        with:
          push: true
          tags: user/app:latest
          secrets: |
            GIT_AUTH_TOKEN=${{ secrets.ARTIFACTORY_TOKEN}}
#          build-args: |
#            arg1=value1
#            arg2=value2
      -
        name: Image digest
        run: echo ${{ steps.docker_build.outputs.digest }}
