# This is a basic workflow to help you get started with Actions

name: read-default-variables

# Controls when the action will run. 
on:
  # Triggers the workflow on push or pull request events but only for the main branch
  push:
      paths:
      - '.github/workflows/read**'
  pull_request:
    branches: [ main ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2

      # Runs a single command using the runners shell
      - name: read out a default var
        run: echo ${GITHUB_ACTOR}

      # Runs a set of commands using the runners shell
      - name: Read out multiple variables
        run: |
              echo CI=${CI}
              echo GITHUB_WORKFLOW=${GITHUB_WORKFLOW}
              echo GITHUB_RUN_ID=${GITHUB_RUN_ID}
              echo GITHUB_RUN_NUMBER=${GITHUB_RUN_NUMBER}
              echo GITHUB_ACTION=${GITHUB_ACTION}
              echo GITHUB_ACTIONS=${GITHUB_ACTIONS}
              echo GITHUB_ACTOR=${GITHUB_ACTOR}
              echo GITHUB_REPOSITORY=${GITHUB_REPOSITORY}
              echo GITHUB_EVENT_NAME=${GITHUB_EVENT_NAME}
              echo GITHUB_EVENT_PATH=${GITHUB_EVENT_PATH}
              echo GITHUB_WORKSPACE=${GITHUB_WORKSPACE}
              echo GITHUB_SHA=${GITHUB_SHA}
              echo GITHUB_REF=${GITHUB_REF}
              echo GITHUB_HEAD_REF=${GITHUB_HEAD_REF}
              echo GITHUB_BASE_REF=${GITHUB_BASE_REF}
              echo GITHUB_SERVER_URL=${GITHUB_SERVER_URL}
              echo GITHUB_API_URL=${GITHUB_API_URL}
              echo GITHUB_GRAPHQL_URL=${GITHUB_GRAPHQL_URL}
              echo
              echo ****FINISHED READING VARIABLES!****
              
              
      # Runs a set of shell commands to show env and workspace info
      - name: Run a multiline script
        run: |
          echo 1. What is in this directory?
          ls -a
          echo
          echo 2. Is Java installed?
          java -version
          echo
          echo 3. Is Git installed?
          git --version
          echo
          echo 4. What build tools are instaleld?
          mvn --version
          gradle --version
          ant -version
          echo
          echo 5. BLANK
          echo
          echo 6. Where are the Selenium jars?
          echo $SELENIUM_JAR_PATH
          echo
          echo 7. What is the workspace location?
          echo $RUNNER_WORKSPACE
          echo 8. Who is running this script?
          whoami
          echo
          echo 9. How is the disc laid out?
          df
          echo 10. What enviornment variiables are there?
          env
          
          
          
          
      - name: Read out multiple variables
        run: |          
          echo  "END of Readout" 
          
